ManagerController = module.exports = require('./ManagerController')
CustomerController = module.exports = require('./CustomerController')
RoomController = module.exports = require('./RoomController')
PaymentController = module.exports = require('./PaymentController')
FeedbackController = module.exports = require('./FeedbackController')